-dontwarn kotlin.**
-keep class kotlin.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-keep class okhttp3.** { *; }
-keep class okio.** { *; }
-dontwarn com.airbnb.lottie.**
-keep class com.airbnb.lottie.** { *; }
-dontwarn androidx.**
-keep class androidx.** { *; }
-keep class co.median.android.jlrnql.** { *; }
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
